### ISSUE TITLE
Add README.md for type registry

### ISSUE THREAD

**Issue by bmelville** [kubernetes/deployment-manager#50] opened 2015-11-12 17:06 UTC

**Comment by jackgr** [comment] 2015-11-12 22:23
Is this a duplicate of #43?

**Comment by bmelville** [comment] 2015-11-13 00:03
Should link to type registry documentation and include information on process for submitting new types (e.g., PRs and issues)

**Comment by jackgr** [comment] 2015-11-16 21:00
Fixed by #69 and folowing.

**Closed by jackgr** 2015-11-16 21:00 UTC
Labels: priority/P0
