### ISSUE TITLE
Template output parameters

### ISSUE THREAD

**Issue by bmelville** [kubernetes/deployment-manager#111] opened 2015-11-19 21:27 UTC
Support the ability for templates to have output values which can be referenced by other resources.

e.g.,

resources:
- name: r1
  type: replicatedservice.py
- name: r2
  type: repliatedservice.py
  properties:
    env:
      r1Port: $(ref.r1.port)

**Comment by jackgr** [comment] 2015-12-17 17:11
Duplicate of #54.

**Closed by jackgr** 2015-12-17 17:11 UTC
Labels: duplicate, priority/P2
